/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stock.repositories;

import java.util.List;
import org.springframework.data.repository.CrudRepository;

/**
 * The basic methods of this class (create, find...) are automatically generated by spring data
 * @author madhava
 */

public interface ProductRepository extends CrudRepository<ProductEntity, Long> {

    /**
     * Find all the products from this category. The method is automatically 
     * created by spring data based on the name.
     * @param category Category name
     * @return 
     */
    public List<ProductEntity> findByCategory(String category);
    
}
